### PR TITLE
Add recommendations to HTML & CSS folder

### LINKED ISSUE #6: Add recommendations to HTML & CSS folder
The current repo structure looks good. Now all we need is some information to share! The first goal will be to add a list of recommendations to the HTML & CSS course folder.

### PR DESCRIPTION
**Pull request by SkySails**
This is just a suggestion as to how we can structure the content inside each folder. This approach uses the folder's `readme.md` file to display the contents, which results in a quick overview as soon as the folder is opened. The advantages of this vs. dividing each folder into subfolders are primarily ease-of-access, clarity, and easy management/moderation.

Additionally, I've tried to use the capabilities of the Markdown language to my advantage in an effort to structure the list while also making it pretty to the eye!

This would close #6

### CODE REVIEW

**Comment by SkySails** [comment]
Also - the filenames of the main directories were renamed to their original filenames. This comes after my suggestion in #5 to remove blank spaces in filenames, in which I wasn't clear about the fact that the original directories should be left as-is for readability in this repository.

**Comment by r-eldblad** [comment]
LGTM! I actually had a similar idea in my head when I created the README.md files in the first place. To give users a overview for each course, and also provide a way for people to navigate through all the information.

**Review by r-eldblad — APPROVED** [review]
LGTM! I actually had a similar idea in my head when I created the README.md files in the first place. To give users a overview for each course, and also provide an easy way for people to navigate through all the information.

**Comment by r-eldblad** [comment]
Not a big deal, but I found a typo in the readme.md, in the last heading I suspect you meant to say "Tools & Resources". Other than that, good job!

**Comment by SkySails** [comment]
You are correct indeed! I was lazy and copy-pasted the same typo multiple times. Will fix with another commit!

**Comment by Talica2005** [comment]
Det är svårt att förstå från vilken steg måste jag börja? T.ex. att försöka lägga mapp med screenshot lektioners .. Jag är förvirrad ... och jag vet inte om jag skriver kommentarerna här korrekt?

**Comment by SkySails** [comment]
@Talica2005 Det låter som en god idé! Du behöver inte alls hålla dig till mitt `readme.md`-dokument, du kan göra en egen mapp för skärmbilder. För att göra det så kan du förslagsvis göra en egen gren i detta repo, sedan lägga till en mapp med dina skärmbilder och slutligen göra en pull request. Just detta kommentarsfält gäller enbart #7 , så kommentaren hör nog inte hemma här egentligen!

**Comment by hannesqvarnstrom** [comment]
looks great, time to merge?

**Review by hannesqvarnstrom — COMMENTED** [review]
LGTM

**Pull request merged**
