### PR TITLE
Create gitguide.md

### PR DESCRIPTION
**Pull request by ottoreimers**
People can add more Git guides here

### CODE REVIEW

**Comment by SkySails** [comment]
Was the `gitguide.md` file supposed to be outside of all the main project structure? Seems like it would fit better under `Programmeringsmetodik` along with the changes in #8

**Review by SkySails — CHANGES_REQUESTED** [review]
Please move the file inside `Programmeringsmetodik`!

**Review by hannesqvarnstrom — APPROVED** [review]
excellent start to file

**Review by SkySails — APPROVED** [review]
LGTM!

**Comment by ottoreimers** [comment]
Thank you all!

**Pull request merged**
